### ISSUE TITLE
How to upgrade package to new tag ?

### ISSUE THREAD

**Issue by mailtoharshit** [wbond/packagecontrol.io#73]
I upgraded [Weave Github Repo](https://github.com/mailtoharshit/Weave/tree/v1.0.3) with new Tag from (v1.0.1) to (v1.0.3), I want people to download this version from package control which has few bugs fixes and enhancements, here are my questions

 1- How do I ensure package-control takes latest tag from my repo ? 
 2 - How do I deliver latest changes to people who have my package already installed ?
3. What other changes I have to do in configuration to link to latest tags ? 

Other details 
- [w.json](https://github.com/wbond/package_control_channel/blob/master/repository/w.json)

I uninstalled and installed weave package in my sublime and noticed that packagecontrol is still pulling tag (v1.0.1) in Sublime see [this](https://www.evernote.com/shard/s176/sh/ac368ea1-4e07-42e1-ab39-024faa2a6152/782478e6dac5bf65)

**Comment by wbond** [comment]
The crawler checks each package about once every hour or so. It will automatically find new tags and will show it at https://packagecontrol.io/packages/Weave. You can look at that page to see when the crawler last scanned your package.

By default users will be automatically upgraded the next time they restart Sublime Text and it has been an hour since the last check of the channel.

**Comment by mailtoharshit** [comment]
Brilliant Thanks !!
